### ISSUE TITLE
ios version

### ISSUE THREAD

**Issue by ozcan-durak** [fellowGC/ShovelMapboxNavigation#1]
Hi thanks for the opensource contribution,

Can you please explain how you have implemented IOS version. Not sure how to integrate with our current project. Docs maybe ?

Regards

**Comment by fellowGC** [comment]
Sorry for the inconvenience but, this is not the working version. Forgot I even uploaded this on GitHub. I am going to be publishing a new version of this with Capacitor v4. Going to submit it to the Community Plugins as well with documentation.

Regards,

**Comment by ozcan-durak** [comment]
Thanks for the reply.

When will you release a new version ?

**Comment by fellowGC** [comment]
Hi, 
I will probably uploade a new version of this with better documentation by the end of next week.
